version: "3.9"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    command: --storage.host=${CB_HOST} --storage.username=${CB_USER} --storage.password=${CB_PSWD}
    container_name: try-cb-api-mm

  frontend:
    build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
    ports:
      - 8081:8081
    container_name: try-cb-fe-mm

  db:
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "9102:9102"
      - "11210:11210"
    expose:
      - "8091"
      - "8094"
    container_name: couchbase-sandbox-7.0.0-mm
